import {StyleSheet, Text, View} from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  btnLogin: {
    backgroundColor: '#FAF0F8',
    borderWidth: 1,
    borderColor: '#B792F2',
    width: 254,
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txt1: {
    fontSize: 20,
    fontWeight: '500',
    color: '#3A3030',
    fontFamily: 'Kanit-Medium',
  },
  txt2: {
    fontSize: 14,
    fontWeight: '500',
    color: '#677294',
    fontFamily: 'Kanit-Medium',
  },
  txt3: {
    fontSize: 16,
    fontWeight: '500',
    color: '#677294',
    fontFamily: 'Kanit-Medium',
  },
  viewCard: {
    backgroundColor: '#fff',
    shadowOffset: {width: -2, height: 4},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    height: 130,
    width: 370,
    marginVertical: 10,
    justifyContent: 'center',
    borderRadius: 8,
  },
  viewImg: {
    // backgroundColor: 'red',
    width: 92,
    height: 100,
    borderRadius: 6,
    overflow: 'hidden',
    borderColor: '#E7E5E4',
    borderWidth: 1,
  },
  viewRow1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
  },
  viewRow2: {
    flexDirection: 'row',
  },
  viewIn: {
    backgroundColor: '#0EBE7F',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  viewRow3: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputSeach: {
    backgroundColor: '#fff',
    height: 54,
    borderRadius: 6,
    width: 280,
    fontSize: 18,
    fontWeight: '500',
    color: '#333333',
    fontFamily: 'Kanit-Regular',
  },
  viewContentTxtInput: {
    width: '85%',
    height: 54,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: '#fff',
    alignSelf: 'center',
    paddingHorizontal: 15,
    borderRadius: 8,
    marginTop: 5,
  },
 
  viewAdd: {
    backgroundColor: '#107532',
    width: 112,
    height: null,
    borderRadius: 4,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  btnSave: {
    backgroundColor: '#107532',
    width: '85%',
    height: 50,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 50,
  },
  modalContent: {
    flex: 0.2,
    backgroundColor: '#fff',
    borderRadius: 4,
    justifyContent: 'space-around',
    paddingVertical: 5,
  },
  btnDelete: {
    backgroundColor: 'red',
    width: 140,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  iconBin: {
    width: 100,
    height: 100,
    alignSelf: 'center',
    position: 'absolute',
    bottom: 140,
  },
  txt4: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333333',
    fontFamily: 'Kanit-Medium',
  },
});

export default styles;
